# Generated by Django 4.0.4 on 2022-05-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_birth_year_user_created_at_user_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytranslation',
            old_name='activity',
            new_name='name',
        ),
        migrations.AddField(
            model_name='activity',
            name='name_en',
            field=models.CharField(default='act01', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resourceusage',
            name='name_en',
            field=models.CharField(default='act01', max_length=20),
            preserve_default=False,
        ),
    ]
